apiVersion: apps/v1
kind: Deployment
metadata:
  name: educacion-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: educacion-backend-app
  template:
    metadata:
      labels:
        app: educacion-backend-app
    spec:
      containers:
        - name: educacion-backend-container
          image: 365227208102.dkr.ecr.us-east-2.amazonaws.com/educacion-backend:latest
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: 'production'
          resources:
            requests:
              memory: '100Mi'
              cpu: '100m'
            limits:
              memory: '200Mi'
              cpu: '200m'
