export enum EventoTipo {
  CICLO = 'Ciclo',
  CHARLA = 'Charla',
  COLOQUIO = 'Coloquio',
  CONFERENCIA = 'Conferencia',
  CONGRESO = 'Congreso',
  CONVENCION = 'Convención',
  EXPOSICION = 'Exposición',
  FORO = 'Foro',
  MESA_REDONDA = 'Mesa redonda',
  PANEL = 'Panel',
  SEMINARIO = 'Seminario',
  SIMPOSIO = 'Simposio',
  CULTURA = 'Cultural',
  DEPORTIVO = 'Deportivo',
  CHARLA_VIRTUAL = 'Charla virtual',
  CONFERENCIA_VIRTUAL = 'Conferencia virtual',
}
